-- V16: CondicionPuesto — agregar campos de horario, días laborales, modalidad y tipo de inicio.
-- Propósito: Eliminar valores hardcodeados del BasesPdfGenerator y permitir configuración real
--            por convocatoria en la sección IV "Condiciones Esenciales del Contrato".
-- Tablas afectadas: TBL_CONDICION_PUESTO
-- Rollback: Ver sección al final del script.
-- Todos los campos son NULLABLE porque existen registros previos sin estos datos.

-- 1. Horario de trabajo — formato HH:MM (24h), ej. "08:30", "17:00"
ALTER TABLE TBL_CONDICION_PUESTO ADD HORARIO_INICIO VARCHAR2(5);
ALTER TABLE TBL_CONDICION_PUESTO ADD HORARIO_FIN    VARCHAR2(5);

COMMENT ON COLUMN TBL_CONDICION_PUESTO.HORARIO_INICIO IS 'Hora de inicio de jornada, formato HH:MM. Ej: 08:30';
COMMENT ON COLUMN TBL_CONDICION_PUESTO.HORARIO_FIN   IS 'Hora de fin de jornada, formato HH:MM. Ej: 17:00';

-- 2. Días laborales — texto libre, ej. "Lunes a viernes", "Lunes a sábado"
ALTER TABLE TBL_CONDICION_PUESTO ADD DIAS_LABORALES VARCHAR2(100);

COMMENT ON COLUMN TBL_CONDICION_PUESTO.DIAS_LABORALES IS 'Días de la semana laborales. Ej: Lunes a viernes';

-- 3. Modalidad del servicio — PRESENCIAL, REMOTO, SEMIPRESENCIAL
ALTER TABLE TBL_CONDICION_PUESTO ADD MODALIDAD_SERVICIO VARCHAR2(30);

ALTER TABLE TBL_CONDICION_PUESTO ADD CONSTRAINT CK_CONDICION_MODALIDAD
    CHECK (MODALIDAD_SERVICIO IN ('PRESENCIAL', 'REMOTO', 'SEMIPRESENCIAL') OR MODALIDAD_SERVICIO IS NULL);

COMMENT ON COLUMN TBL_CONDICION_PUESTO.MODALIDAD_SERVICIO IS
    'Modalidad de prestación: PRESENCIAL, REMOTO o SEMIPRESENCIAL (D.Leg. 1057)';

-- 4. Tipo de inicio del contrato — indica si la fecha de inicio es inmediata, fija o a la firma
ALTER TABLE TBL_CONDICION_PUESTO ADD TIPO_INICIO_CONTRATO VARCHAR2(30);

ALTER TABLE TBL_CONDICION_PUESTO ADD CONSTRAINT CK_CONDICION_TIPO_INICIO
    CHECK (TIPO_INICIO_CONTRATO IN ('INMEDIATO', 'FECHA_FIJA', 'A_LA_FIRMA') OR TIPO_INICIO_CONTRATO IS NULL);

COMMENT ON COLUMN TBL_CONDICION_PUESTO.TIPO_INICIO_CONTRATO IS
    'Tipo de inicio: INMEDIATO (a la suscripción), FECHA_FIJA (se especificará en contrato), A_LA_FIRMA';

-- ── ROLLBACK (ejecutar solo si se necesita revertir esta migración) ──
-- ALTER TABLE TBL_CONDICION_PUESTO DROP CONSTRAINT CK_CONDICION_TIPO_INICIO;
-- ALTER TABLE TBL_CONDICION_PUESTO DROP CONSTRAINT CK_CONDICION_MODALIDAD;
-- ALTER TABLE TBL_CONDICION_PUESTO DROP COLUMN TIPO_INICIO_CONTRATO;
-- ALTER TABLE TBL_CONDICION_PUESTO DROP COLUMN MODALIDAD_SERVICIO;
-- ALTER TABLE TBL_CONDICION_PUESTO DROP COLUMN DIAS_LABORALES;
-- ALTER TABLE TBL_CONDICION_PUESTO DROP COLUMN HORARIO_FIN;
-- ALTER TABLE TBL_CONDICION_PUESTO DROP COLUMN HORARIO_INICIO;
