-- V23: Flag de notificación ORH tras Entrevista Personal (E27)
-- Mismo patrón que NOTIFICACION_CODIGOS_ENVIADA (E25)
ALTER TABLE TBL_CONVOCATORIA ADD (
    NOTIFICACION_ENTREVISTA_ENVIADA NUMBER(1) DEFAULT 0 NOT NULL
);
